server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config   #服务名称
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lnp1996/microservicecloud-config.git  #GitHub上面的git仓库名字


